## Indexing and Slicing
Elements and subarrays of NumPy arrays are accessed using the standar square brackets notation that is also used with Python lists. Within the square brackets, a variety of different index formats are used for different types of element selection. In general, the expression within the brackets is a tuple, where each item in the tuple is a specification of which elements to select from each axis (dimension) of the array.

![axis-array](images/axis-array.png)

### One-Dimensional Arrays
Along a single axis, integers are used to select single elements, and so-called slices are used to select ranges and sequences of elements. Positive integers are used to index elements from the beginning of the array (index starts at $0$), and negative integers are used to index elements from the end of the array, where the last element is indexed with $-1$, the second to last element with $-2$, and so on.

Slices are specified using the $:$ notation that is also used for Python lists. In this notation, a range of elements can be selected using an expression like $m:n$, which selects elements starting with $m$ and ending with $n-1$ (note that the *nth* element is not included). 

The slice $m:n$ can also be written more explicitly as $m:n:1$, where the number $1$ specifies that every element between $m$ and $n$ should be selected. To select every second element between $m$ and $n$, use $m:n:2$ and to select every $p$ elements, use $m:n:p$, and so on. If $p$ is negative, elements are returned in reversed order starting from $m$ to $n-1$ (which implies that $m$ has to be larger than $n$ in this case). The following table is a summary of the indexing and slicing operations for NumPy arrays.

#### Examples of Array Indexing and Slicing Expressions

Expression | Description
 :--- | :--- 
 **a[m]** | Select element at index $m$, where $m$ is an integer (start counting from $0$).
 **a[-m]** | Select the *nth* element from the end of the list, where $n$ is an integer. The last element in the list is addressed as $-1$, the second to last element as $-2$, and so on.
 **a[m:n]** | Select elements with index starting at $m$ and ending at $n-1$ ($m$ and $n$ are integers).   
 **a[:] or a[0:-1]** | Select all elements in the given axis.  
 **a[:n]** | Select elements starting with index $0$ and going up to index $n-1$ (integer).  
 **a[m:] or a[m:-1]** | Select elements starting with index $m$ (integer) and going up to the last element in the array. 
 **a[m:n:p]** | Select elements with index $m$ through $n$ (exclusive), with increment $p$.  
 **a[::-1]** | Select all the elements, in reverse order. 

 
 The following examples demonstrate index and slicing operations for NumPy arrays. To begin with, consider an array with a single axis (dimension) that contains a sequence of integers between $0$ and $10$:

In [1]:
# Importing the NumPy library
import numpy as np

a = np.arange(0, 11)

In [2]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Note that the end value 11 is not included in the array. To select specific elements from this array, for example, the first, the last, and the *5th* element, we can use integer indexing:  

In [3]:
a[0] # The first element

0

In [4]:
a[-1] # The last element

10

In [5]:
a[4] # The fifth element, at index 4

4

To select a range of element, say from the second to the second-to-last element, selecting every element and every second element, respectively, we can use index slices:

In [6]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

To select the first five and the last five elements from an array, we can use the slices [ : 5] and [-5 : ], since if $m$ or $n$ is omitted in $m:n$, the defaults are the beginning and the end of the array, respectively. 

In [8]:
a[:5]

array([0, 1, 2, 3, 4])

In [9]:
a[-5:]

array([ 6,  7,  8,  9, 10])

To reverse array and select only every second value, we can use the slice [ : : -2], as shown in the following example:

In [10]:
a[::-2]

array([10,  8,  6,  4,  2,  0])

### Multidimensional Arrays
With multidimensional arrays, element selections like those introduced in the previous section we can be applied on each axis (dimension). The result is a reduced array where each element matches the given section rules. As a specific example, consider the following two-dimensional array.

In [11]:
f = lambda m, n: n + 10 * m

In [12]:
A = np.fromfunction(f, (6, 6), dtype=np.int)

In [13]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

We can extract columns and rows from this two-dimensional array using a combination of slice and integer indexing:

In [14]:
A[:, 1] # the second column

array([ 1, 11, 21, 31, 41, 51])

In [15]:
A[1, :] # the second row

array([10, 11, 12, 13, 14, 15])

By applying a slice on each of the array axes, we can extract subarrays (submatrices in this two-dimensional example):

In [16]:
A[:3, :3] # upper half diagonal block matrix

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [17]:
A[3:, :3] # lower left off-diagonal block matrix

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

With element spacing other that $1$, submatrices made up from nonconsecutive elements can be extracted:

In [18]:
A[::2, ::2] # every second element starting from 0, 0

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [19]:
A[1::2, 1::3] # every second and third element starting from 1, 1

array([[11, 14],
       [31, 34],
       [51, 54]])

This ability to extract subsets of data from a multidimensional array is a simple but very powerful feature with many data processing applications.

### Views
Subarrays that are extracted from arrays using slice operations are alternative views of the same underlying array data. That is, they are arrays that refer to the same data in the memory as the original array, but with a different strides configuration. When elements in a view are assigned new values, the values of the original array are therefore also updated. For example,

In [20]:
B = A[1:5, 1:5]

In [21]:
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [22]:
B[:, :] = 0

In [23]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

Subarrays that are extracted from arrays using slice operations are alternative views of the same underlying array data. That is, they are arrays that refer to the same data in the memory as the original array, but with a different strides configuration. When elements in a view are assigned new values, the values of the original array are therefore also updated. For example:

In [24]:
C = B[1:3, 1:3].copy()

In [25]:
C

array([[0, 0],
       [0, 0]])

In [26]:
C[:, :] = 1 # this does not affect B since C is a copy of the view B[1:3, 1:3]

In [27]:
C

array([[1, 1],
       [1, 1]])

In [28]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In addition to the copy attribute of the ndarray class, an array can also be copied using the function np.copy or, equivalently, using the np.array function with the keyword argument copy=True.

### Fancy Indexing and Boolean-Valued Indexing
NumPy provides a convenient method to index arrays, called fancy indexing. With fancy indexing, an array can be indexed with another NumPy array, a Python list, or a sequence of integers, whose values select elements in the indexed array. Consider the
following example: we first create a NumPy array with $11$ floating-point numbers, and then index the array with another NumPy array (and Python list), to extract element numbers $0$, $2$, and $4$ from the original array:

In [29]:
A = np.linspace(0, 1, 11); A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [30]:
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [31]:
A[[0, 2, 4]] # The same thing can be accomplished by indexing with a Python list

array([0. , 0.2, 0.4])

This method of indexing can be used along each axis (dimension) of a multidimensional NumPy array. It requires that the elements in the array or list used for indexing are integers.

Another variant of indexing NumPy arrays is to use Boolean-valued index arrays. In this case, each element (with values True or False) indicates whether or not to select the element from the list with the corresponding index. That is, if element $n$ in the indexing array of Boolean values is True, then element n is selected from the indexed array. 

If the value is False, then element n is not selected. This index method is handy when filtering out elements from an array. For example, to select all the elements from the array A (as defined in the preceding section) that exceed the value $0.5$, we can use the following combination of the comparison operator applied to a NumPy array and indexing using a Boolean-valued array:

In [32]:
A > 0.5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [33]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

Unlike arrays created by using slices, the arrays returned using fancy indexing and Boolean-valued indexing are not views but rather than new independent arrays. Nonetheless, it is possible to assign values to elements selected using fancy indexing: 

In [34]:
A = np.arange(10)

In [35]:
indices = [2, 4, 6]

In [36]:
B = A[indices]

In [37]:
B[0] = -1 # this does not affect A

In [38]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
A[indices] = -1 # this alters A

In [40]:
A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

and likewise for Boolean-valued indexing:

In [41]:
A = np.arange(10)

In [42]:
B = A[A > 5]

In [43]:
B[0] = -1 # this does not affect A

In [44]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
A[A > 5] = -1 # this alters A

In [46]:
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

A visual summary of different methods to index NumPy arrays is given in Figure 2-1. Note that each type of indexing we have discussed here can be independently applied to each dimension of an array.

![summary-of-indexing-methods](images/visual-summary-of-indexing-methods.png)

**Figure 2-1.** Visual summary of indexing methods for NumPy arrays. These diagrams represent NumPy arrays of shape (4, 4), and the highlighted elements are those that are selected using the indexing expression shown above the block representations of the arrays.