## Vectors, Matrices, and Multidimensional Arrays

### A brief introduction to NumPy library
NumPy is an open-source software library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. 

The NumPy library provides data structures for representing a rich variety of arrays and methods and functions for operating on such arrays. NumPy provides the numerical backend for nearly every scientific or technical library for Python.


### Importing the modules
In order to use the NumPy library, we need to import it in our program. By convention,
the NumPy module imported under the alias np, like so:

In [1]:
import numpy as np

After this, we can access functions and classes in the numpy module using the np
namespace.

### The NumPy Array Object
The core of the NumPy library is the data structures for representing multidimensional arrays of homogeneous data. Homogeneous refers to all elements in an array having the same data type. The main data structure for multidimensional arrays in NumPy is the ndarray class. In addition to the data stored in the array, this data structure also contains important metadata about the array, such as its shape, size, data type, and other attributes. 

#### Basic Attributes of the ndarray Class

Attribute | Description   
 :--- | :--- 
 **shape** | A tuple that contains the number of elements (i.e., the length) for each dimension (axis) of the array.
 **size** | The total number elements in the array. 
 **ndim** | Number of dimensions (axes).
 **nbytes** | Number of bytes used to store the data.
 **dtype** | The data type of the elements in the array. 

The following example demonstrates how these attributes are accessed for an instance data of the class ndarray:

In [2]:
data = np.array([[1, 2] , [3, 4], [5, 6]])

In [3]:
type(data)

numpy.ndarray

In [4]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
data.ndim

2

In [6]:
data.shape

(3, 2)

In [7]:
data.size

6

In [8]:
data.dtype

dtype('int32')

In [9]:
data.nbytes

24

Here the ndarray instance data is created from a nested Python list using the function np.array. In the preceding example, the data is a two dimentional array (data.ndim) of shape 3 x 2, as indicated by data.shape, and in total it contains six elements (data.size) of type int32 (data.dtype), which amounts to a total size of 24 bytes (data.nbytes).

### Data Types
The dtype attribute of the ndarray object describes the data type of each element in the array (since NumPy arrays are homogeneous, all elements have the same data type). The basic numerical data types supported in NumPy are show in the following table. 

#### Basic Numerical Data Types Available in NumPy

dtype | Variants | Description   
 :- | :- | :-
 **int** | int8, int16, int32, int64 | Integers
 **uint** | uint8, uint16, uint32, uint64 | Unsigned (nonnegative) integers 
 **bool** | Bool | Boolean (True or False)
 **float** | float16, float32, float64, float128 | Floating-point numbers
 **complex** | complex64, complex128, complex256 | Complex-valuated floating-point numbers
 
Nonnumerical data types, such as strings, objects, and user-defined compound types, are also supported.
For numerical work the most important data types are int (for integers), float (for floating-point numbers), and complex (for complex floating-point numbers). 

Each of these data types comes in different sizes, such as int32 for 32-bit integers, int64 for 64-bit integers, etc. 
It is usually not necessary to explicitly choose the bit size of the data type to work with, but it is often necessary to explicitly choose wether to use arrays of integers, floating-point, numbers, or complex values.

The following example demonstrates how to use the dtype attribute to generate arrays of integer-valued, float-valued, and complex-valued elements:

In [10]:
np.array([1, 2, 3], dtype=np.int)

array([1, 2, 3])

In [11]:
np.array([1, 2, 3], dtype=np.float)

array([1., 2., 3.])

In [12]:
np.array([1, 2, 3], dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

Once a NumPy array is created, its dtype cannot be changed, other than by creating a new copy with type-casted array values. Typecasting an array is straightforward and can be done using either the np.array function:

In [13]:
data = np.array([1, 2, 3], dtype=np.float)

In [14]:
data

array([1., 2., 3.])

In [15]:
data.dtype

dtype('float64')

In [16]:
data = np.array(data, dtype=np.int)

In [17]:
data.dtype

dtype('int32')

In [18]:
data

array([1, 2, 3])

In [19]:
data = np.array([1, 2, 3], dtype=np.float)

In [20]:
data

array([1., 2., 3.])

In [21]:
data.astype(np.int)

array([1, 2, 3])

When computing with NumPy arrays, the data type might get promoted from one type to another, if required by the operation. For example, adding float-valued and complex-valued arrays, the resulting array is a compled-valued array:

In [22]:
d1 = np.array([1, 2, 3], dtype=float)

In [23]:
d2 = np.array([1, 2, 3], dtype=complex)

In [24]:
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [25]:
(d1 + d2).dtype

dtype('complex128')

In some cases, depending on the application and its requirements, it is essential to create arrays with data type appropriately set to, for example, int or complex. The default type is float. Consider the following example:

In [26]:
np.sqrt(np.array([-1, 0, 1]))

<ipython-input-26-18cc2be45d00>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(np.array([-1, 0, 1]))


array([nan,  0.,  1.])

In [27]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

Here, using the np.sqrt function to compute the square root of each element in an array gives different results depending on the data type of the array. Only when the data type of the array is complex is the square root of -1 resulting in the imaginary unit (denoted 1j in Python).

### Real and Imaginary Parts
Regardless of the value of the dtype attribute, all NumPy array instances have attributes real and imag for extracting the real and imaginary parts of the array, respectively:

In [28]:
data = np.array([1, 2, 3], dtype=complex)

In [29]:
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [30]:
data.real

array([1., 2., 3.])

In [31]:
data.imag

array([0., 0., 0.])

The same functionality is also provided by the function np.real and np.imag, which also can be applied to other array-like objets, such as Python lists. Note that Python itself has support of complex numbers, and the imag and real attributes are also available for Python scalars.