## Reshaping and Resizing
When working with data in array from, it is often useful to rearrange arrays and alter the way they are interpreted. For example, an $N \times N$ matrix array could be rearranged into a vector of length $N^{2}$, or a set of one-dimensional arrays could be concatenated together or stacked next to each other to form a matrix. NumPy provides a rich set of functions of this type of manipulation. 

#### Summary of NumPy Functions for Manipulating the Dimensions and the Shape of Arrays

Function/Method | Description   
 :--- | :--- 
 **np.reshape, np.ndarray.reshape** | Reshape an N-dimensional array. The total number of elements must remain the same.
 **np.ndarray.flatten** | Creates a copy of an N-dimensional array, and reinterpret it as a one-dimensional array (i.e., all dimension are collapsed into one). 
 **np.ravel, np.ndarray.ravel** | Create a view (if possible, otherwise a copy) of a N-dimensional array in which is interpreted as a one-dimensional array. 
 **np.squeeze** | Removes axes with length 1. 
 **np.expand_dims, np.newaxis** | Add a new axis (dimension) of length 1 to an array, where np.newaxis is used with array indexing.
 **np.transpose, np.ndarray.transpose, np.ndarray.T** | Transpose the array. The transpose operation corresponds to reversing (or more generally, permuting) the axes of the array.
 **np.hstack** | Stacks a list of arrays horizontally (along axis 1): for example, given a list of column vectors, appends the columns to form a matrix.
 **np.vstack** | Stacks a list of arrays vertically (along axis 0): for example, given a list of row vectors, appends the rows to form a matrix. 
 **np.dstack** | Stacks arrays depth-wise (along axis 2).
 **np.concatenate** | Creates a new array by appending arrays after each other, along a given axis.
 **np.resize** | Resizes an array. Creates a new copy of the original array, with the requested size. If necessary, the original array will be repeated to fill up the new array.
 **np.append** | Appends an element to an array. Creates a new copy of the array.
 **np.insert** | Inserts a new element at a given position. Creates a new copy of the array.
 **np.delete** | Deletes an element at a given position. Creates a new copy of the array.
 
Reshaping an array does not require modifying the underlying array data; it only changes in how the data is interpreted, by redefining the array's strides attribute. An example, of this type of operation is a $2 \times 2$ array (matrix) that is reinterpreted as a $1 \times 4$ array (vector).
 
In NumPy, the function np.reshape, or the ndarray class method reshape, can be used to reconfigure how the underlying data is interpreted. It takes an array and the new shape of the array as arguments:

In [1]:
# Importing the NumPy library
import numpy as np

data = np.array([[1, 2], [3, 4]])

In [2]:
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

In [3]:
data.reshape(4)

array([1, 2, 3, 4])

It is necessary that the requested new shape of the array match the number of elements in the original size. However, the number of axes (dimensions) does not need to be conserved, as illustrated in the previous example, where in the first case, the new array has dimension 2 and shape (1, 4), while in the second case, the new array has dimension 1 and shape (4,).

This example also demonstrates two different ways of invoking the reshape operation: using the function np.reshape and the ndarray method reshape. Note that reshaping an array produces a view of the array, and if an independent copy of the array is needed, the view has to be copied explicitly (e.g., using np.copy).

The np.ravel (and its corresponding ndarray method) is a special case of reshape, which collapses all dimensions of an array and returns a flattened one-dimensional array with a length that corresponds to the total number of elements in the original array. The ndarray method flatten performs the same function but returns a copy instead a view.

In [4]:
data = np.array([[1, 2], [3, 4]])

In [5]:
data

array([[1, 2],
       [3, 4]])

In [6]:
data.flatten()

array([1, 2, 3, 4])

In [7]:
data.flatten().shape

(4,)

In addition to reshaping and selecting subarrays, it is often necessary to merge arrays into bigger arrays, for example, when joining separately computed or measured data series into a higher-dimensional array, such as a matrix.
For this task, NumPy provides the functions np.vstack, for vertical stacking of, for example, rows into a matrix, and np.hstack for horizontal stacking of, for example, columns into a matrix. The function np.concatenate provides similar functionality, but it takes a keyword argument axis that specifies the axis along which the arrays are to be concatenated.

The shape of the arrays passed to np.hstack, np.vstack, and np.concatenate is important to achieve the desired type of array joining. For example, consider the following cases: say we have one-dimensional arrays of data, and we want to stack them vertically to obtain a matrix where the rows are mede up of the one-dimensional arrays. We can use np.vstack to achieve this:

In [8]:
data = np.arange(5)

In [9]:
data

array([0, 1, 2, 3, 4])

In [10]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

If we instead want to stack the arrays horizontally, to obtain a matrix where the arrays are the columns vectors, we might first attempt something similar using np.hstack:

In [11]:
data = np.arange(5)

In [12]:
data

array([0, 1, 2, 3, 4])

In [13]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

The number of elements in a NumPy array cannot be changed once the array has been created. To insert, append, and remove elements from a NumPy array, for example, using the function np.append, np.insert, and np.delete, a new array must be created and the data copied to it. It may sometimes be tempting to use these functions to grow or shrink the size of a NumPy array, but due to the overhead of creating new arrays and copying the data, it is usually a good idea to preallocate arrays with size such that they do not later need to be resized.