### Vectorized Expressions
The purpose of storing numerical data in arrays is to be able to process the data with concise vectorized expressions that represent batch operations that are applied to all elements in the array. Efficient use of vectorized expressions eliminates the need of many explicit for loops. This results in less verbose code, better maintainability, and higher-performing code. NumPy implements functions and vectorized operations corresponding to most fundamental mathematical functions and operator. Many of these functions and operations act on arrays on an elementwise basis, and binary operations requiere all arrays in an expression to be of compatible size. 

The meaning of compatible size is normally that the variables in an expression represent either scalars or arrays of the same size and shape. More generally, a binary operation involving two arrays is well defined if the arrays can be broadcasted into the same shape and size.

In the case of an operation between a scalar and an array, broadcasting refers to the scalar being distributed and the operation applied to each element in the array. When an expression contains arrays of unequal sizes, the operations may still be well defined if the smaller of the array can be broadcasted ("effectively expanded") to match the larger array according to NumPy's broadcasting rule: an array can be broadcasted over another array if their axes on a one-by-one basis either have the same length or if either of them have length 1. If the number of axes of the two arrays is no equal, the array with fewer axes is padded with new axes of length 1 from the left until the numbers of dimensions of the two arrays agree.

Two simplest examples that illustrates array broadcasting are shown in **Figure 2-2**: a $3\times3$ matrix is added to a $1\times3$ row vector and a $3\times1$ column vector, respectively, and in both cases the result is a $3\times3$ matrix.
![broadcasting-visualization](images/broadcasting-visualization.png)
**Figure 2-2.** Visualization of broadcasting of row and column vectors into the shape of a matrix. The highlighted elements represents true elements of the arrays, while the light gray-shaded elements describe the broadcasting of the elements of the array of smaller size.

### Arithmetic Operations
The standard arithmetic operations with NumPy arrays perform elementwise operations. For example, the addition, subtraction, multiplication, and division of equal-sized arrays:

In [1]:
# Importing the NumPy library
import numpy as np

x = np.array([[1, 2], [3, 4]])

In [2]:
y = np.array([[5, 6], [7, 8]])

In [3]:
x + y

array([[ 6,  8],
       [10, 12]])

In [4]:
y - x

array([[4, 4],
       [4, 4]])

In [5]:
x * y

array([[ 5, 12],
       [21, 32]])

In [6]:
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In operations between scalars and arrays, the scalar values is applied to each element in the array, as one could expect:

In [7]:
x * 2

array([[2, 4],
       [6, 8]])

In [8]:
2 ** x

array([[ 2,  4],
       [ 8, 16]], dtype=int32)

In [9]:
y / 2

array([[2.5, 3. ],
       [3.5, 4. ]])

In [10]:
(y / 2).dtype

dtype('float64')

Note that the dtype of the resulting array for an expression can be promoted if the computation requires it, as shown in the preceding example with division between an integer array and an integer scalar, which in that case resulted in an array with a dtype that is np.float64

If an arithmetic operation is performed on array with incompatible size or shape, a ValueError exception is raised:

In [11]:
x = np.array([1, 2, 3, 4,]).reshape(2, 2)

In [12]:
z = np.array([1, 2, 3, 4])

In [13]:
x / z

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

Here the array x has shape (2, 2) and the array z has shape (4,) which cannot be broadcasted into a form that is compatible with (2, 2). If, on the other hand, z has shape (2,), (2, 1) or (1, 2), then it can broadcasted to the shape (2, 2) by effectively repeating the array z along the axis with length 1. Let's first consider an example with an array z of shape (1, 2), where the first axis (axis 0) has length 1:

In [14]:
z = np.array([[2, 4]])

In [15]:
z.shape

(1, 2)

Dividing the array x with array z is equivalent to dividing x with an array zz that is constructed by repeating (here using np.concatenate) the row vector z to obtain an array z has the same dimensions as x:

In [16]:
x / z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [17]:
zz = np.concatenate([z, z], axis=0)

In [18]:
zz

array([[2, 4],
       [2, 4]])

In [19]:
x / zz

array([[0.5, 0.5],
       [1.5, 1. ]])

Let's also consider the example in which the array z has shape (2, 1) and where the second axis (axis 1) has length 1:

In [20]:
z = np.array([[2], [4]])

In [21]:
z.shape

(2, 1)

In this case, dividing x with z is equivalent to dividing x with an array zz that is constructed by repeating the column vector z until a matrix with the same dimensions as x is obtained.

In [22]:
x / z

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [23]:
zz = np.concatenate([z, z], axis=1)

In [24]:
zz

array([[2, 2],
       [4, 4]])

In [25]:
x / zz

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In summary, these examples show how arrays with shape (1, 2) and (2, 1) are broadcasted to the shape (2, 2) of the array x when the operation x / z is performed. In both cases, the result of the operation x / z is the same as first repeating the smaller array z along its axis of length 1 to obtain a new array zz with the same shape as x and then performing the equal-sized array operation x / zz.

However, the implementation of the broadcasting does not explicitly perform this expansion and the corresponding memory copies, but it can be helpful to think of the array broadcasting in these terms.
A summary of the operators for arithmetic operations with NumPy arrays is given in **Table 2-6**. These operators use the standard symbols used in Python. The result of an arithmetic operation with one or two arrays is a new independent array, with its own data in the memory.

**Table 2-6.** Operators for Elementwise Arithmetic Operation in NumPy arrays

Operator | Operation   
 :--- | :--- 
 **+, +=** | Addition
 **-, -=** | Subtraction
 ***, *=** | Multiplication
 **/, /=** | Division
 **//, //=** | Integer Division
 **\*\*, \*\*=** | Exponentiation
 
 Use inplace operation (see **Table 2-6**) can reduce the memory footprint and improve performance. As an example of inplace operators, consider the following two statements, which have the same effect:

In [26]:
x = x + y

In [27]:
x += y

The two expressions have the same effect, but in the first case, x is reassigned to a new array, while in the second case, the values of array x are updated inplace. Extensive use of inplace operators tends to impair code readability, and implace operators should therefore be used only when necessary.

### Elementwise Functions
In addition to arithmetic expressions using operators, NumPy provides vectorized functions for elementwise evaluation of many elementary mathematical functions and operations. **Table 2-7** gives a summary of elementary mathematical functions in NumPy.

**Table 2-7.** Selection of NumPy Functions for Elementwise Elementary Mathematical Functions

NumPy Function | Description   
 :--- | :--- 
 **np.cos, np.sin, np.tan** | Trigonometric functions.
 **np.arccos, np.arcsin, np.arctan** | Inverse trigonometric functions.
 **np.cosh, np.sinh, np.tanh** | Hyperbolic trigonometric functions.
 **np.arccosh, np.arcsinh, np.arctanh** | Inverse hyperbolic trigonometric functions.
 **np.sqrt** | Square root.
 **np.exp** | Exponential.
 **np.log, np.log2, np.log10** | Logarithms of base e, 2, and 10, respectively.
 
 For example, the np.sin function (which takes only one argument) is used to compute the sine function for all values in the array:

In [28]:
x = np.linspace(-1, 1, 11)

In [29]:
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [30]:
y = np.sin(np.pi * x)

In [31]:
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

Here we also used the constant np.pi and the function np.round to round the values of y to four decimals. Like the np.sin function, many of the elementary math functions take one input array and produce one output array. In contrast, many of the mathematical operator functions (see **Table 2-8**) operates on two input arrays returns one array:

In [32]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
np.sin(x) ** 2 + np.cos(x) ** 2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Table 2-8.** Summary of NumPy Functions for Elementwise Mathematical Operations

NumPy Function | Description   
 :--- | :--- 
 **np.add, np.subtract, np.multiply, np.divide** | Addition, subtraction, multiplication, and division of two NumPy arrays.
 **np.power** | Raises first input argument to the power of the second input argument (applied elementwise).
 **np.remainder** | The remainder of division.
 **np.reciprocal** | The reciprocal (inverse) of each element.
 **np.real, np.imag, np.conj** | The real part, imaginary part, and the complex conjugate of the elements in the input arrays.
 **np.sign, np.abs** | The sign, and the absolute value.
 **np.floor, np.ceil, np.rint** | Convert to integer values.
 **np.round** | Rounds to a given number of decimals.
 
Note that in this example, np.add and the operator + are equivalent, and for normal use the operator should be used. Occasionally it is necessary to define new functions that operate on NumPy arrays on an element-by-element basis.

A good way to implement such functions is to express it in terms of already existing NumPy operators and expressions, but in cases when this is not possible, the np.vectorize function can be a convenient tool. For example, consider the following implementation of the Heaviside step function, which works for scalar input:

In [34]:
def heaviside(x):
    return 1 if x > 0 else 0

In [35]:
heaviside(-1)

0

In [36]:
heaviside(1.5)

1

However, unfortunately this function does not work for NumPy array input:

In [37]:
x = np.linspace(-5, 5, 11)

In [38]:
heaviside(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Using np.vectorize the scalar Heaviside function can be converted into a vectorized function that works with NumPy arrays as input:

In [39]:
heaviside = np.vectorize(heaviside)

In [40]:
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

Although the function returned by np.vectorize works with arrays, it will be relatively slow since the original function must be called for each element in the array. There are much better ways to implementing this particular function using arithmetic with Boolean-valued arrays.

In [41]:
def heaviside(x):
    return 1.0 * (x > 0)

np.vectorize can be a quick and convenient way to vectorize a function written for scalar input. In addition to NumPy's functions for elementary mathematical function, as summarized in **Table 2-7**, there are also numerous functions in NumPy for mathematical operations. A summary of a selection of these functions is given in **Table 2-8**.


### Aggregate Functions
NumPy provides another set of functions for calculating aggregates for NumPy arrays, which take an array as input and by default return a scalar as output. For example, statistics such as averages, standard deviations, and variances of the values in the input array, and functions for calculating the sum and the product of elements in an array, are all agreggate functions.

A summary of aggregate functions is given in **Table 2-9**. All of these functions are also available as methods in the ndarray class. For example, np.mean(data) and data.mean() in the following example are equivalent.

In [42]:
data = np.random.normal(size=(15, 15))
data.shape

(15, 15)

In [43]:
np.mean(data)

-0.001885575906998969

In [44]:
data.mean()

-0.001885575906998969

**Table 2-9.** NumPy Functions for Calculating Aggregates of NumPy Arrays

NumPy Function | Description
 :--- | :--- 
 **np.mean** | The average of all values in the array. 
 **np.std** | Standard deviation.
 **np.var** | Variance.
 **np.sum** | Sum of all elements.
 **np.prod** | Product of all elements.
 **np.cumsum** | Cumulative sum of all elements.
 **np.cumprod** | Cumulative product of all elements
 **np.min, np.max** | The minimum/maximum value in an array. 
 **np.argmin, np.argmax** | The index of the minimum/maximum value in an array.  
 **np.all** | Returns True if all elements in the argument array are nonzero.
 **np.any** | Returns True if any of the elements in the argument array is nonzero. 

By default, the functions in **Table 2-9** aggregate over the entire input array. Using the axis keyword argument with these functions, and their corresponding ndarray methods, it is possible to control over which axis in the array aggregation is carried out. The axis argument can be an integer, which specifies the axis to aggregate values over. 

I many cases the axis argument can also be a tuple of integers, wich specifies multiple axes to aggregate over. The following example demonstrates how calling the aggregate function np.sum on the array of shape (5, 10, 15) reduces the dimensionality of the array depending on the values of the axis argument.

In [45]:
data = np.random.normal(size=(5, 10, 15))

In [46]:
data.sum(axis=0).shape

(10, 15)

In [47]:
data.sum(axis=(0, 2)).shape

(10,)

In [48]:
data.sum()

-9.567723148365971

A visual illustration of how aggregation over all elements, over the first axis, and over the second axis of a $3\times3$ array is shown in **Figure 2-3**. In this example, the data array is filled with integers between 1 and 9: 

In [49]:
data = np.arange(1, 10).reshape(3, 3)

In [50]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

![Array-aggregation-functions](images/Array-aggregation-functions.png)
**Figure 2-3**. Illustration of array aggregation functions along all axes (left), the first axis (center), and the second axis (right) of a two-dimensional array of shape 3x3.

and we compute the aggregate sum of the entire array, over the axis 0, and over axis 1, respectively:

In [51]:
data.sum()

45

In [52]:
data.sum(axis=0)

array([12, 15, 18])

In [53]:
data.sum(axis=1)

array([ 6, 15, 24])

### Set Operations
The python language provides a convenient set data structure for managing unordered collections of unique objects. The  NumPy array class ndarray can also be used to describe such sets, and NumPy contains functions for operating on sets stored as NumPy arrays. These functions are summarized in **Table 2-11.** Using NumPy arrays to describe and operate on sets allows expressing certain operations in vectorized form. 

For example, testing if the values in a NumPy array are included in a set can be done using the np.in1d function, which tests for the existence of each element of its first argument in the array passed as the second argument. To see how this works, consider the following example: first, to ensure that a NumPy array is a proper set, we can use the np.unique function, which returns a new array with unique values:

In [54]:
a = np.unique([1, 2, 3, 3]); a

array([1, 2, 3])

In [55]:
b = np.unique([2, 3, 4, 4, 5, 6, 5]); b

array([2, 3, 4, 5, 6])

In [56]:
np.in1d(a, b)

array([False,  True,  True])

**Table 2-11.** NumPy Functions for Operating on Sets

Function | Description   
 :--- | :--- 
 **np.unique** | Creates a new array with unique elements, where each value only appears once.
 **np.in1d** | Tests for the existence of an array of elements in another array. 
 **np.intersect1d** | Returns an array with elements that are contained in two given arrays.
 **np.setdiff1d** | Returns an array with elements that are contained in one, but not the other, of two given arrays.
 **np.union1d** | Returns an array with elements that are contained in either, or both, of two given arrays.
 
 Here, the existence of each element in a in the set b was tested, and the result is a Boolean-valued. Note that we can use the *in* keyword to test for the existence of single elements in a set represented as NumPy arrays:

In [57]:
1 in a

True

In [58]:
1 in b

False

To test if a is a subset of b, we can use the np.in1d, as in the previous example, together with the aggregation function np.all (or the corresponding ndarray method):

In [59]:
np.all(np.in1d(a, b))

False

The method numpy.any() returns True if at least one element in a NumPy array evaluates to True while numpy.all() returns True only if all elements in a NumPy array evaluate to True.

The standard set operations union (the set of elements included in either or both sets), intersection (elements included in both sets), and difference (elements included in one of the sets but not the other) are provided by np.union1d, np.intersect1d, and np.setdiff1d, respectively:

In [60]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

In [61]:
np.intersect1d(a, b)

array([2, 3])

In [62]:
np.setdiff1d(a, b)

array([1])

In [63]:
np.setdiff1d(b, a)

array([4, 5, 6])

### Operations on Arrays
In addition to elementwise and aggregation functions, some operations act on arrays as a whole and produce a transformed array of the same size. An example of this type of operation is the transpose, which flips the order of the axes of an array. For the special case of two-dimensional arrays i.e., a matrix, the transpose simply exchanges rows and columns: 

In [64]:
data = np.arange(9).reshape(3, 3)

In [65]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

The transpose function np.transpose also exists as a method in ndarray and as the special method name ndarray.T. For an arbitrary N-dimensional array, the transpose operation reverses all the axes, as can be seen from the following example (note that the shape attribute is used here for display the number of values along each axis of the array).

In [67]:
data = np.random.randn(1, 2, 3, 4, 5)

In [68]:
data.shape

(1, 2, 3, 4, 5)

In [69]:
data.T.shape

(5, 4, 3, 2, 1)

The np.fliplr (flip left-right) and np.flipud (flip up-down) functions perform operations that are similar to the transpose: they reshuffle the elements of an array so that the elements in rows (np.fliplr) or columns (np.flipud) are reversed, and the shape of the output array is the same as the input.

The np.rot90 function rotates the elements in the first two axes in an array by 90 degrees, and like the transpose function, it can change the shape of the array. **Table 2-12** gives a summary of NumPy functions for common array operations.

**Table 2-12.** Summary of NumPy Functions for Array Operations

 Function | Description
 :--- | :--- 
 **np.transpose, np.ndarray.transpose, np.ndarray.T** | The transpose (reverse axes) of an array. 
 **np.fliplr / np.flipup** | Reverse the elements in each row/column.
 **np.rot90** | Rotates the elements along the first two axes by 90 degrees.
 **np.sort, np.ndarray.sort** | Sort the elements of an array along a given specified axis (which default to the last axis of the array). The np.ndarray method sort performs the sorting in place, modifying the input array.